//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obsequy.Communication.Email.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Obsequy.Communication.Email.Templates.TemplateResources", typeof(TemplateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Provider Response Accepted
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Member],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		A response has been accepted by a family member.
        ///	&lt;/p&gt;
        ///	&lt;ul&gt;
        ///		&lt;li&gt;[City], [State]&lt;/li&gt;
        ///		&lt;li&gt;Quote: $[Quote]&lt;/li&gt;
        ///		&lt;li&gt;Paid: $[BalancePaid]&lt;/li&gt;
        ///		&lt;li&gt;Due: $[BalanceDue]&lt;/li&gt;
        ///		&lt;li&gt;Response: [Id]&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;p&gt;
        ///		Updated at [Modified].
        ///	&lt;/p&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string AcceptedResponse {
            get {
                return ResourceManager.GetString("AcceptedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Consumer Account Registered
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Member],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		A consumer account is registered and has submitted a portfolio for bidding.
        ///	&lt;/p&gt;
        ///	&lt;ul&gt;
        ///		&lt;li&gt;Location: [City], [State]&lt;/li&gt;
        ///		&lt;li&gt;Portfolio: [Id]&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;p&gt;
        ///		Updated at [Modified].
        ///	&lt;/p&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string ConsumerRegistration {
            get {
                return ResourceManager.GetString("ConsumerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 3.2//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///
        ///	&lt;style&gt;
        ///		header {
        ///			height: 40px;
        ///			background-color: #1db7e3;
        ///		}
        ///
        ///		header .content {
        ///			margin-top: 10px;
        ///			margin-left: 20px;
        ///			font-size: 20px;
        ///			color: #ffffff;
        ///		}
        ///
        ///		footer {
        ///			height: 40px;
        ///			background-color: #1db7e3;
        ///			font-size: 12px;
        ///			color: #ffffff;
        ///		}
        ///
        ///		footer .content {
        ///			margin-top: 10px;
        ///			margin-left: 40px;
        ///			color: #ffffff;
        ///		}
        ///		
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Account Activated
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Member] of [ProviderName],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		We are pleased to let you know that your account has been activated and you are able to submit quotes on &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt;. 
        ///	&lt;/p&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string ProviderAccountActivated {
            get {
                return ResourceManager.GetString("ProviderAccountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Account Rejected
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Member] of [ProviderName],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		We are sorry to inform you that your account request has been rejected by &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt;. Please contact us if you would like to know more information.
        ///	&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ProviderAccountRejected {
            get {
                return ResourceManager.GetString("ProviderAccountRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Provider Account Registered
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Member],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		A new provider account has been registered and is ready for review.
        ///	&lt;/p&gt;
        ///	&lt;ul&gt;
        ///		&lt;li&gt;Name: [Name]&lt;/li&gt;
        ///		&lt;li&gt;Phone: [Phone]&lt;/li&gt;
        ///		&lt;li&gt;Email: [Email]&lt;/li&gt;
        ///		&lt;li&gt;Portfolio: [Id]&lt;/li&gt;
        ///	&lt;/ul&gt;
        ///	&lt;p&gt;
        ///		Updated at [Modified].
        ///	&lt;/p&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string ProviderRegistration {
            get {
                return ResourceManager.GetString("ProviderRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [FirstName],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		We noticed that you created a portfolio using &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt; and we want you to know that we are sorry for your loss and are here to help you with funeral planning.
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		A funeral request has been created but has not been submitted. If you are ready to receive responses to your request, please submit your portfolio on &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt; so we can match you up with funeral providers.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Your Quote has been Accepted
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Name],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		Congratulations! &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt; is please to inform you that a family has accepted your response to their request for funeral services. 
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		Here is what you need to do now:
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		Please login to your profile on &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt; to revisit details of the funeral service to which you resp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseAccepted {
            get {
                return ResourceManager.GetString("ResponseAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Your Quote has been Rejected
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Name],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		Unfortunately we must inform you that a family has accepted another Funeral Home’s response to their request for funeral services.
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		We cannot say for certain why the family chose another Funeral Home, but know that affordability is key to the success of funeral homes being chosen. So please be as competitive as possible when submitting y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseAutoRejected {
            get {
                return ResourceManager.GetString("ResponseAutoRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		A New Bidding Opportunity is Available
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Name],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		A family has requested funeral services in your area. Please login to your profile on the &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt; website to review details of the requested services. Once you&apos;ve logged in to &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt;, you may begin submitting your response.
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		After you have reviewed the services the fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseAvailable {
            get {
                return ResourceManager.GetString("ResponseAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		You have a Response to Your Request
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [FirstName],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		We are humbled that you have trusted &lt;a href=&quot;[Domain]&quot;&gt;Funeral-Choice&lt;/a&gt; to help you make the arrangements that best fit your budget and honor the life of your loved-one. We are pleased to let you know that we have found Funeral Homes willing to provide the services you requested in and around the area indicated the memorial ceremony was  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponsePending {
            get {
                return ResourceManager.GetString("ResponsePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subject-content&quot;&gt;
        ///	&lt;div&gt;
        ///		Your Quote has been Rejected
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;message-content&quot;&gt;
        ///	&lt;p&gt;
        ///		Dear [Name],
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		Unfortunately we must inform you that a family has accepted another Funeral Home’s response to their request for funeral services.
        ///	&lt;/p&gt;
        ///	&lt;p&gt;
        ///		We cannot say for certain why the family chose another Funeral Home, but know that affordability is key to the success of funeral homes being chosen. So please be as competitive as possible when submitting y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseUserRejected {
            get {
                return ResourceManager.GetString("ResponseUserRejected", resourceCulture);
            }
        }
    }
}
